export const PAGINATION = {
  DEFAULT_PAGE: 1,
  DEFAULT_PAGE_SIZE: 24,
  MAX_PAGE_SIZE: 100,
} as const;

export const DOWNLOAD = {
  MAX_CONCURRENT_PER_USER: 5,
  MAX_RETRIES: 3,
  RETRY_DELAY_MS: 5000,
  SPEED_CALC_WINDOW_MS: 3000,
} as const;

export const STORAGE = {
  DEFAULT_LIMIT_BYTES: 50 * 1024 * 1024 * 1024, // 50GB
  THUMBNAIL_WIDTH: 400,
  THUMBNAIL_HEIGHT: 400,
} as const;

export const SCRAPE = {
  DEFAULT_DELAY_MS: 2000,
  MAX_CONCURRENT_PROFILES: 3,
  REQUEST_TIMEOUT_MS: 30000,
} as const;
